# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControlWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 700)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 80, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 171, 18))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rB_plot_k = QtWidgets.QRadioButton(self.layoutWidget)
        self.rB_plot_k.setChecked(True)
        self.rB_plot_k.setObjectName("rB_plot_k")
        self.horizontalLayout.addWidget(self.rB_plot_k)
        self.rB_plot_r = QtWidgets.QRadioButton(self.layoutWidget)
        self.rB_plot_r.setObjectName("rB_plot_r")
        self.horizontalLayout.addWidget(self.rB_plot_r)
        self.rB_plot_q = QtWidgets.QRadioButton(self.layoutWidget)
        self.rB_plot_q.setObjectName("rB_plot_q")
        self.horizontalLayout.addWidget(self.rB_plot_q)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(30, 250, 261, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 70, 261, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 100, 25))
        self.label_2.setMaximumSize(QtCore.QSize(100, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 100, 25))
        self.label_3.setMaximumSize(QtCore.QSize(100, 25))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 221, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dB_kmin = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.dB_kmin.setMaximumSize(QtCore.QSize(80, 25))
        self.dB_kmin.setAlignment(QtCore.Qt.AlignCenter)
        self.dB_kmin.setMaximum(20.0)
        self.dB_kmin.setSingleStep(0.1)
        self.dB_kmin.setProperty("value", 3.0)
        self.dB_kmin.setObjectName("dB_kmin")
        self.horizontalLayout_2.addWidget(self.dB_kmin)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMaximumSize(QtCore.QSize(30, 25))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.dB_kmax = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.dB_kmax.setMaximumSize(QtCore.QSize(80, 25))
        self.dB_kmax.setAlignment(QtCore.Qt.AlignCenter)
        self.dB_kmax.setMaximum(20.0)
        self.dB_kmax.setSingleStep(0.1)
        self.dB_kmax.setProperty("value", 12.0)
        self.dB_kmax.setObjectName("dB_kmax")
        self.horizontalLayout_2.addWidget(self.dB_kmax)
        self.layoutWidget2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 110, 221, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dB_rmin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.dB_rmin.setMaximumSize(QtCore.QSize(80, 25))
        self.dB_rmin.setAlignment(QtCore.Qt.AlignCenter)
        self.dB_rmin.setMaximum(10.0)
        self.dB_rmin.setSingleStep(0.1)
        self.dB_rmin.setProperty("value", 1.0)
        self.dB_rmin.setObjectName("dB_rmin")
        self.horizontalLayout_3.addWidget(self.dB_rmin)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setMaximumSize(QtCore.QSize(30, 25))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.dB_rmax = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.dB_rmax.setMaximumSize(QtCore.QSize(80, 25))
        self.dB_rmax.setAlignment(QtCore.Qt.AlignCenter)
        self.dB_rmax.setMaximum(10.0)
        self.dB_rmax.setSingleStep(0.1)
        self.dB_rmax.setProperty("value", 3.0)
        self.dB_rmax.setObjectName("dB_rmax")
        self.horizontalLayout_3.addWidget(self.dB_rmax)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 225, 131, 25))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 420, 111, 21))
        self.label_6.setObjectName("label_6")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(30, 440, 261, 161))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(30, 10, 80, 30))
        self.label_7.setMaximumSize(QtCore.QSize(80, 30))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.cB_FitSpace = QtWidgets.QComboBox(self.frame_2)
        self.cB_FitSpace.setGeometry(QtCore.QRect(150, 10, 80, 30))
        self.cB_FitSpace.setMaximumSize(QtCore.QSize(80, 30))
        self.cB_FitSpace.setObjectName("cB_FitSpace")
        self.cB_FitSpace.addItem("")
        self.cB_FitSpace.addItem("")
        self.cB_FitSpace.addItem("")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(30, 40, 80, 30))
        self.label_10.setMaximumSize(QtCore.QSize(80, 30))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.cB_WindowType = QtWidgets.QComboBox(self.frame_2)
        self.cB_WindowType.setGeometry(QtCore.QRect(150, 40, 80, 30))
        self.cB_WindowType.setMaximumSize(QtCore.QSize(80, 30))
        self.cB_WindowType.setObjectName("cB_WindowType")
        self.cB_WindowType.addItem("")
        self.cB_WindowType.addItem("")
        self.cB_WindowType.addItem("")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(30, 70, 80, 30))
        self.label_8.setMaximumSize(QtCore.QSize(80, 30))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.cB_kweight = QtWidgets.QComboBox(self.frame_2)
        self.cB_kweight.setGeometry(QtCore.QRect(150, 70, 80, 30))
        self.cB_kweight.setMaximumSize(QtCore.QSize(80, 30))
        self.cB_kweight.setObjectName("cB_kweight")
        self.cB_kweight.addItem("")
        self.cB_kweight.addItem("")
        self.cB_kweight.addItem("")
        self.cB_kweight.addItem("")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(30, 100, 80, 25))
        self.label_11.setMaximumSize(QtCore.QSize(80, 30))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.dB_window_dk = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.dB_window_dk.setGeometry(QtCore.QRect(150, 100, 80, 25))
        self.dB_window_dk.setMaximumSize(QtCore.QSize(80, 30))
        self.dB_window_dk.setMaximum(10.0)
        self.dB_window_dk.setSingleStep(0.1)
        self.dB_window_dk.setProperty("value", 1.0)
        self.dB_window_dk.setObjectName("dB_window_dk")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(30, 130, 80, 25))
        self.label_12.setMaximumSize(QtCore.QSize(80, 30))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.dB_window_dr = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.dB_window_dr.setGeometry(QtCore.QRect(150, 130, 80, 25))
        self.dB_window_dr.setMaximumSize(QtCore.QSize(80, 30))
        self.dB_window_dr.setMaximum(10.0)
        self.dB_window_dr.setSingleStep(0.1)
        self.dB_window_dr.setProperty("value", 1.0)
        self.dB_window_dr.setObjectName("dB_window_dr")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(210, 610, 80, 30))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(30, 610, 111, 30))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.pB_refresh = QtWidgets.QPushButton(Form)
        self.pB_refresh.setGeometry(QtCore.QRect(240, 85, 60, 60))
        self.pB_refresh.setMaximumSize(QtCore.QSize(80, 80))
        self.pB_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rotate360anticlockwise2red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pB_refresh.setIcon(icon)
        self.pB_refresh.setIconSize(QtCore.QSize(30, 30))
        self.pB_refresh.setObjectName("pB_refresh")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 145, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 30, 241, 19))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rB_wModel = QtWidgets.QCheckBox(self.layoutWidget3)
        self.rB_wModel.setObjectName("rB_wModel")
        self.horizontalLayout_5.addWidget(self.rB_wModel)
        self.rB_wFit = QtWidgets.QCheckBox(self.layoutWidget3)
        self.rB_wFit.setObjectName("rB_wFit")
        self.horizontalLayout_5.addWidget(self.rB_wFit)
        self.layoutWidget4 = QtWidgets.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 30, 261, 40))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cB_showParams = QtWidgets.QCheckBox(self.layoutWidget4)
        self.cB_showParams.setMaximumSize(QtCore.QSize(160, 30))
        self.cB_showParams.setObjectName("cB_showParams")
        self.horizontalLayout_4.addWidget(self.cB_showParams)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pB_Fit = QtWidgets.QPushButton(self.layoutWidget4)
        self.pB_Fit.setEnabled(True)
        self.pB_Fit.setMinimumSize(QtCore.QSize(100, 40))
        self.pB_Fit.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pB_Fit.setFont(font)
        self.pB_Fit.setStyleSheet("color: rgb(0, 0, 255);")
        self.pB_Fit.setObjectName("pB_Fit")
        self.horizontalLayout_4.addWidget(self.pB_Fit)

        self.retranslateUi(Form)
        self.cB_FitSpace.setCurrentIndex(1)
        self.cB_WindowType.setCurrentIndex(0)
        self.cB_kweight.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "plot space"))
        self.rB_plot_k.setText(_translate("Form", "k"))
        self.rB_plot_r.setText(_translate("Form", "r"))
        self.rB_plot_q.setText(_translate("Form", "q"))
        self.label_2.setText(_translate("Form", "k range[A^-1]"))
        self.label_3.setText(_translate("Form", "r range[A]"))
        self.label_4.setText(_translate("Form", "to"))
        self.label_5.setText(_translate("Form", "to"))
        self.label.setText(_translate("Form", "FT range/Fit range"))
        self.label_6.setText(_translate("Form", "Fitting conditions"))
        self.label_7.setText(_translate("Form", "Fit space"))
        self.cB_FitSpace.setItemText(0, _translate("Form", "k"))
        self.cB_FitSpace.setItemText(1, _translate("Form", "r"))
        self.cB_FitSpace.setItemText(2, _translate("Form", "q"))
        self.label_10.setText(_translate("Form", "Window"))
        self.cB_WindowType.setItemText(0, _translate("Form", "kaiser"))
        self.cB_WindowType.setItemText(1, _translate("Form", "hanning"))
        self.cB_WindowType.setItemText(2, _translate("Form", "welch"))
        self.label_8.setText(_translate("Form", "k weight"))
        self.cB_kweight.setItemText(0, _translate("Form", "3"))
        self.cB_kweight.setItemText(1, _translate("Form", "2"))
        self.cB_kweight.setItemText(2, _translate("Form", "1"))
        self.cB_kweight.setItemText(3, _translate("Form", "0"))
        self.label_11.setText(_translate("Form", "dk"))
        self.label_12.setText(_translate("Form", "dr"))
        self.label_9.setText(_translate("Form", "deg. Freedom"))
        self.groupBox_2.setTitle(_translate("Form", "Plot Model/Fit"))
        self.rB_wModel.setText(_translate("Form", "Model"))
        self.rB_wFit.setText(_translate("Form", "Fit"))
        self.cB_showParams.setText(_translate("Form", "Show params"))
        self.pB_Fit.setText(_translate("Form", "Fit"))

